import { Geist, Geist_Mono } from "next/font/google";
import { DM_Sans } from "next/font/google"; // Import DM Sans
import "./globals.css";
import Navber from "./components/Navber/page";
import Footer from './components/footer/page';

// Load fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Add weights if needed
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dmSans.variable} antialiased`}
      >
        <Navber />
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
